pipeline {
    agent any
    environment {
        PATH = "/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node/node-v20.11.0-linux-arm64/bin:$PATH"
    }
    stages {
        stage('Build Frontend') {
            steps {
                // Frontend 빌드 스크립트
                echo "Frontend build"
                sh "pwd"
                dir("B206-frontend-repo"){
                    sh "pwd"
                    sh "npm install --force"
                    sh "CI=false npm run build"
                    sh 'ssh -i ~/.ssh/id_rsa ubuntu@i10b206.p.ssafy.io "rm -rf /home/ubuntu/frontend/build/"'
                    sh 'ssh -i ~/.ssh/id_rsa ubuntu@i10b206.p.ssafy.io "mkdir /home/ubuntu/frontend/build/"'
                    sh 'scp -i ~/.ssh/id_rsa -r ./build/ ubuntu@i10b206.p.ssafy.io:/home/ubuntu/frontend/'
                    sh 'scp -i ~/.ssh/id_rsa ./dockerfile ubuntu@i10b206.p.ssafy.io:/home/ubuntu/frontend/dockerfile'
                    sh 'scp -i ~/.ssh/id_rsa ./init.sh ubuntu@i10b206.p.ssafy.io:/home/ubuntu/frontend/init.sh'
                    sh 'scp -i ~/.ssh/id_rsa ./nginx.conf ubuntu@i10b206.p.ssafy.io:/home/ubuntu/frontend/nginx.conf'
                    sh 'ssh -i ~/.ssh/id_rsa ubuntu@i10b206.p.ssafy.io "cd /home/ubuntu/frontend && sh init.sh"'
    
                }
                
                echo "Frontend build complete"
            }
        }
    }
}